# Generated by Django 3.2.5 on 2021-07-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stock_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.ManyToManyField(to='main.Stock'),
        ),
    ]
