# Generated by Django 3.2.5 on 2021-07-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
