# Generated by Django 3.2.5 on 2021-07-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.ManyToManyField(blank=True, null=True, to='main.Stock'),
        ),
    ]
