# Generated by Django 3.2.5 on 2021-07-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
